name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

# # 1. 서명 키 및 환경 변수 설정 (빌드 전 수행)
#     - name: Decode Keystore
#       run: echo '${{ secrets.KEY_STORE }}' | base64 -d > ./app/upload-keystore.jks

    - name: Generate local.properties
      run: |
        echo '${{ secrets.KEY_STORE }}' | base64 -d > ./app/upload-keystore.jks
        echo "STORE_PATH=upload-keystore.jks" > ./local.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> ./local.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> ./local.properties
        echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> ./local.properties

    - name: Create Google Services JSON
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 2. 플레이스토어용 AAB 빌드
    - name: Build Release Bundle (AAB)
      run: ./gradlew :app:bundleRelease

    # 3. Google Play 업로드 (내부 테스트 트랙)
    - name: Upload to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonRaw: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.your.package.name # 본인의 패키지명으로 변경
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: internal # internal, alpha, beta, production 중 선택
        status: completed


