name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # 1. 서명 키 및 환경 변수 설정
    - name: Decode Keystore
      run: echo '${{ secrets.KEY_STORE }}' | base64 -d > ./app/upload-keystore.jks

    - name: Generate local.properties
      run: |
        echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> ./local.properties
        echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> ./local.properties
        echo "STORE_PASSWORD=${{ secrets.STORE_PASSWORD }}" >> ./local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 2. 플레이스토어용 AAB 빌드 (버전 코드 자동 주입)
    - name: Build Release Bundle (AAB)
      # github.run_number를 사용하여 매 실행마다 1씩 증가하는 숫자를 부여합니다.
      # 현재 스토어 버전이 6이므로, run_number(1부터 시작)에 10을 더해 11, 12... 가 되도록 안전하게 설정했습니다.
      run: ./gradlew :app:bundleRelease -PversionCode=$(( ${{ github.run_number }} + 10 ))

    # 3. Google Play 업로드
    - name: Upload to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICES_JSON}}
        packageName: com.jje.timer
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: internal
        status: completed


